# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Noodles in College
email: noodlesincollege@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about Noodles in College.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://noodlesincollege.github.io" # the base hostname & protocol for your site
github_username:  noodlesincollege

# Gems settings
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate: 5